import Head from "next/head";
import Navbar from "../components/Navbar";
import Typed from 'react-typed'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Prashant Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      
    </div>
  );
}
