import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Prashant Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className='flex flex-row bg-slate-800 justify-between w-full h-28 items-center'>
          <h1 className='text-3xl font-mon text-gray-300 ml-4 uppercase cursor-pointer'>Pras<span className='text-red-800'>hant</span></h1>
          <ul className='flex flex-row gap-4 text-gray-200 font-semibold font-mon mr-6'>
              <li className='p-4 cursor-pointer hover:text-red-600'>Home</li>
              <li className='p-4 cursor-pointer hover:text-red-600'>About</li>
              <li className='p-4 cursor-pointer hover:text-red-600'>Contact Us</li>
              <li className='p-4 cursor-pointer hover:text-red-600'>Log In</li>
          </ul>
        </section>
      </main>
    </div>
  )
}
